Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GuardClause:
  Enabled: false